version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: stylecart-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stylecart_dev

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - stylecart-network

  redis:
    image: redis:7.4

    container_name: stylecart-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - stylecart-network

volumes:

  mysql_data:

  redis_data:

networks:

  stylecart-network:
    driver: bridge